Fix installation of pyyaml
"poetry add pyyaml==5.3.1" was failing with:
   AttributeError: 'NoneType' object has no attribute '_source_type'

pyyaml doesn't have any dependencies and various code in PackageInfo() assumes
no dependencies means looking for other sources. from_directory() didn't handle
the case where none of the sources return something and would fail like noted above.

Instead of failing use the last valid result and return it.

Fixes #3362